config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  resources :people
  resources :organizations
end

app/models/organization.rb
class Organization < ActiveRecord::Base


  validates :name, presence: true, uniqueness: true


end

app/models/person.rb
class Person < ActiveRecord::Base

  validates :first_name, presence: true, uniqueness: true
  validates :last_name, presence: true, uniqueness: true
  validates :date_of_birth, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def index
    @organizations = Organization.order(:id)
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      redirect_to organizations_path, notice: "Organization saved successfully"
    else
      render :new
    end
  end

  def edit
    @organization = Organization.find(params[:id])
  end

  def update
    @organization = Organization.find(params[:id])
    if @organization.update(organization_params)
      redirect_to organizations_path, notice: "Organization updated successfully"
    else
      render :edit
    end
  end

  private

  def organization_params
    params.require(:organization).permit(:name)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @people = Person.order(:id)
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to people_path, notice: "Person saved successfully"
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to people_path, notice: "Person updated successfully"
    else
      render :edit
    end

  end

  private

  def person_params
    params.require(:person).permit(:first_name, :last_name, :date_of_birth)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if thingy.errors.any? %>
  <div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
      <div class="alert alert-danger">
        <strong><%= pluralize(thingy.errors.count, "error") %> prohibited this post from being saved:</strong>

        <ul>
          <% thingy.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Rails Practice Validations</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Validation Practice</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "People", people_path %></li>
            <li><%= link_to "Organizations", organizations_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <% if notice %>
        <div class="alert alert-success">
          <%= notice %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/organizations/_form.html.erb
<div class="page-header">
  <h1><%= title %>
      <% if @organization.id %>
        <%= @organization.name_was %></h1>
      <% end %>
</div>

<%= form_for @organization, html: {class: "form-horizontal"} do |f| %>

  <%= render "layouts/errors", thingy: @organization %>

  <div class="form-group">
    <%= f.label :name, class: "control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-2">
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to "cancel", organizations_path, class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<%= render "form", title: "Edit" %>

app/views/organizations/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to "New Organization", new_organization_path, class: "btn btn-info" %>
  </div>
  <h1>Organizations</h1>
</div>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td>
          <%= organization.name %>
        </td>
        <td>
          <%= link_to 'edit', edit_organization_path(organization) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/organizations/new.html.erb
<%= render "form", title: "New Organization" %>

app/views/pages/index.html.erb
<div class="starter-template">
  <h1>Practice Validations</h1>
  <p class="lead">Use this app to add validations.</p>
</div>

app/views/people/_form.html.erb
<div class="page-header">
  <h1><%= title %>
    <% if @person.id %>
      <%= @person.first_name_was %> <%= @person.last_name_was %></h1>
    <% end %>
</div>

<%= form_for @person, html: {class: "form-horizontal"} do |f| %>

  <%= render "layouts/errors", thingy: @person %>

  <div class="form-group">
    <%= f.label :first_name, class: "control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, class: "control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date_of_birth, class: "control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= f.date_field :date_of_birth, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-2">
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to "cancel", people_path, class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/people/edit.html.erb
<%= render "form", title: "Edit" %>

app/views/people/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to "New Person", new_person_path, class: "btn btn-info" %>
  </div>
  <h1>People</h1>
</div>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Date of Birth</th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td>
          <%= person.first_name %>
        </td>
        <td>
          <%= person.last_name %>
        </td>
        <td>
          <%= person.date_of_birth %>
        </td>
        <td>
          <%= link_to 'edit', edit_person_path(person) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/people/new.html.erb
<%= render "form", title: "New User" %>